"""initial schema

Revision ID: 9c40836c7871
Revises:
Create Date: 2026-08-07 09:57:41.364711

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9c40836c7871"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stream_sessions",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("tour_id", sa.String(length=26), nullable=True),
        sa.Column("creator_id", sa.String(length=26), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("quality_ladder", sa.String(length=100), nullable=False),
        sa.Column("ingest_endpoint", sa.String(length=200), nullable=True),
        sa.Column("spatial_audio", sa.Boolean(), nullable=False),
        sa.Column("region_key", sa.String(length=20), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_stream_sessions_creator_id"), "stream_sessions", ["creator_id"], unique=False
    )
    op.create_index(op.f("ix_stream_sessions_status"), "stream_sessions", ["status"], unique=False)
    op.create_index(
        op.f("ix_stream_sessions_tour_id"), "stream_sessions", ["tour_id"], unique=False
    )
    op.create_table(
        "tours",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("title_en", sa.String(length=200), nullable=False),
        sa.Column("title_i18n", sa.JSON(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("creator_id", sa.String(length=26), nullable=True),
        sa.Column("latitude", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("region_key", sa.String(length=20), nullable=False),
        sa.Column("price_cents", sa.Integer(), nullable=False),
        sa.Column("is_free", sa.Boolean(), nullable=False),
        sa.Column("premium", sa.Boolean(), nullable=False),
        sa.Column("duration_sec", sa.Integer(), nullable=True),
        sa.Column("language", sa.String(length=10), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tours_region_key"), "tours", ["region_key"], unique=False)
    op.create_index(op.f("ix_tours_status"), "tours", ["status"], unique=False)
    op.create_index(op.f("ix_tours_title_en"), "tours", ["title_en"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=200), nullable=False),
        sa.Column("display_name", sa.String(length=80), nullable=False),
        sa.Column("locale", sa.String(length=10), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "pois",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("tour_id", sa.String(length=26), nullable=False),
        sa.Column("name_en", sa.String(length=200), nullable=False),
        sa.Column("name_i18n", sa.JSON(), nullable=False),
        sa.Column("t_begin_sec", sa.Numeric(precision=10, scale=3), nullable=False),
        sa.Column("t_end_sec", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column("look_dir", sa.JSON(), nullable=False),
        sa.Column("poi_type", sa.String(length=20), nullable=False),
        sa.Column("description_en", sa.String(length=2000), nullable=True),
        sa.ForeignKeyConstraint(["tour_id"], ["tours.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pois_tour_id"), "pois", ["tour_id"], unique=False)
    op.create_table(
        "sessions",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("user_id", sa.String(length=26), nullable=False),
        sa.Column("device_id", sa.String(length=80), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sessions_user_id"), "sessions", ["user_id"], unique=False)
    op.create_table(
        "hotspots",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("poi_id", sa.String(length=26), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["poi_id"], ["pois.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_hotspots_poi_id"), "hotspots", ["poi_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_hotspots_poi_id"), table_name="hotspots")
    op.drop_table("hotspots")
    op.drop_index(op.f("ix_sessions_user_id"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_index(op.f("ix_pois_tour_id"), table_name="pois")
    op.drop_table("pois")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_tours_title_en"), table_name="tours")
    op.drop_index(op.f("ix_tours_status"), table_name="tours")
    op.drop_index(op.f("ix_tours_region_key"), table_name="tours")
    op.drop_table("tours")
    op.drop_index(op.f("ix_stream_sessions_tour_id"), table_name="stream_sessions")
    op.drop_index(op.f("ix_stream_sessions_status"), table_name="stream_sessions")
    op.drop_index(op.f("ix_stream_sessions_creator_id"), table_name="stream_sessions")
    op.drop_table("stream_sessions")
    # ### end Alembic commands ###
