"""add refresh token hashing

Revision ID: c33628766081
Revises: 9c40836c7871
Create Date: 2026-08-07 10:46:03.849118

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c33628766081"
down_revision: Union[str, None] = "9c40836c7871"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sessions") as batch_op:
        batch_op.add_column(sa.Column("refresh_token_hash", sa.String(length=64), nullable=True))
        batch_op.create_unique_constraint("uq_sessions_refresh_token_hash", ["refresh_token_hash"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sessions") as batch_op:
        batch_op.drop_constraint("uq_sessions_refresh_token_hash", type_="unique")
        batch_op.drop_column("refresh_token_hash")
    # ### end Alembic commands ###
